AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'Vagrantfile'
    - 'Gemfile'
    - 'Berksfile'
    - 'vendor/**/*'
    - '.git/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

EachWithObject:
  Enabled: false

EmptyWhen:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/SignalException:
  EnforcedStyle: semantic

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/TernaryParentheses:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
