AllCops:
  TargetRubyVersion: 2.1

LineLength:
  Enabled: false

EachWithObject:
  Enabled: false

MethodLength:
  Max: 40

Metrics/AbcSize:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/SignalException:
  EnforcedStyle: semantic

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/TernaryParentheses:
  Enabled: false
