AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Vagrantfile'
    - 'Gemfile'
    - 'Berksfile'
    - 'vendor/**/*'
    - '.git/**/*'

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/EmptyWhen:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SignalException:
  EnforcedStyle: semantic

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/TernaryParentheses:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
