name: Splunk Cookbook
group_id: com.cerner.opsinfra
artifact_id: cerner_splunk
version: 1.7.0
doc: tomdoc
package:
  type: cookbook
  files:
    - LICENSE
jira:
  url: http://jira2.cerner.corp
  project: OPSINFRA
  component: 12916
github:
  project_url: https://github.com/cerner/cerner_splunk
  previous_version: 1.6.0
snapshot_repository:
  id: semantic-snapshot
  url: http://repo.snapshot.cerner.corp/nexus/content/repositories/semantic-snapshot/
snapshot_site_repository:
  id: semantic-snapshot-site
  url: http://repo.snapshot.cerner.corp/nexus/content/repositories/semantic-snapshot-site/
repository:
  id: cerner-main-release
  url: http://repo.release.cerner.corp/main/repo/
site_repository:
  id: cerner-main-release-site
  url: http://repo.release.cerner.corp/main/site/
